### ISSUE TITLE
[Server thread/CRITICAL]

### ISSUE THREAD

**Issue by Bruhh1234** [xXMcpeGamerXx03/MuteSystem#1]
hey, when i try to mute with /mute alienware hacking 24, for example
the server crashing

[21:35:59] [Server thread/CRITICAL]: BadMethodCallException: "Cannot serialize Server instance" (EXCEPTION) in "src/pocketmine/Server" at line 2472

Pls fix

**Comment by xXMcpeGamerXx03** [comment]
Thx!

**Comment by Bruhh1234** [comment]
Can you Fix ? xD

**Comment by xXMcpeGamerXx03** [comment]
Yes its fixed

**Comment by xXMcpeGamerXx03** [comment]
https://poggit.pmmp.io/ci/xXMcpeGamerXx03/MuteSystem/~ download the newest

**Comment by Bruhh1234** [comment]
nice i try

**Comment by Bruhh1234** [comment]
it Works you can close the issue

**Comment by RexZetronYT23** [comment]
sus
